// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/onbehalfofhim/secrets-keeper/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSecretRepo is an autogenerated mock type for the SecretRepo type
type MockSecretRepo struct {
	mock.Mock
}

type MockSecretRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretRepo) EXPECT() *MockSecretRepo_Expecter {
	return &MockSecretRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, secret
func (_m *MockSecretRepo) Create(ctx context.Context, secret *models.Secret) (*models.Secret, error) {
	ret := _m.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Secret) (*models.Secret, error)); ok {
		return rf(ctx, secret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Secret) *models.Secret); ok {
		r0 = rf(ctx, secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Secret) error); ok {
		r1 = rf(ctx, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSecretRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - secret *models.Secret
func (_e *MockSecretRepo_Expecter) Create(ctx interface{}, secret interface{}) *MockSecretRepo_Create_Call {
	return &MockSecretRepo_Create_Call{Call: _e.mock.On("Create", ctx, secret)}
}

func (_c *MockSecretRepo_Create_Call) Run(run func(ctx context.Context, secret *models.Secret)) *MockSecretRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Secret))
	})
	return _c
}

func (_c *MockSecretRepo_Create_Call) Return(_a0 *models.Secret, _a1 error) *MockSecretRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepo_Create_Call) RunAndReturn(run func(context.Context, *models.Secret) (*models.Secret, error)) *MockSecretRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ownerID, secretID
func (_m *MockSecretRepo) Delete(ctx context.Context, ownerID uuid.UUID, secretID uuid.UUID) error {
	ret := _m.Called(ctx, ownerID, secretID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, ownerID, secretID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecretRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
//   - secretID uuid.UUID
func (_e *MockSecretRepo_Expecter) Delete(ctx interface{}, ownerID interface{}, secretID interface{}) *MockSecretRepo_Delete_Call {
	return &MockSecretRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, ownerID, secretID)}
}

func (_c *MockSecretRepo_Delete_Call) Run(run func(ctx context.Context, ownerID uuid.UUID, secretID uuid.UUID)) *MockSecretRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretRepo_Delete_Call) Return(_a0 error) *MockSecretRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepo_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockSecretRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, ownerID, secretID
func (_m *MockSecretRepo) GetByID(ctx context.Context, ownerID uuid.UUID, secretID uuid.UUID) (*models.Secret, error) {
	ret := _m.Called(ctx, ownerID, secretID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Secret, error)); ok {
		return rf(ctx, ownerID, secretID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Secret); ok {
		r0 = rf(ctx, ownerID, secretID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerID, secretID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSecretRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
//   - secretID uuid.UUID
func (_e *MockSecretRepo_Expecter) GetByID(ctx interface{}, ownerID interface{}, secretID interface{}) *MockSecretRepo_GetByID_Call {
	return &MockSecretRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ownerID, secretID)}
}

func (_c *MockSecretRepo_GetByID_Call) Run(run func(ctx context.Context, ownerID uuid.UUID, secretID uuid.UUID)) *MockSecretRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretRepo_GetByID_Call) Return(_a0 *models.Secret, _a1 error) *MockSecretRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepo_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.Secret, error)) *MockSecretRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, ownerID
func (_m *MockSecretRepo) List(ctx context.Context, ownerID uuid.UUID) ([]*models.Secret, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Secret, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Secret); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSecretRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
func (_e *MockSecretRepo_Expecter) List(ctx interface{}, ownerID interface{}) *MockSecretRepo_List_Call {
	return &MockSecretRepo_List_Call{Call: _e.mock.On("List", ctx, ownerID)}
}

func (_c *MockSecretRepo_List_Call) Run(run func(ctx context.Context, ownerID uuid.UUID)) *MockSecretRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretRepo_List_Call) Return(_a0 []*models.Secret, _a1 error) *MockSecretRepo_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepo_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*models.Secret, error)) *MockSecretRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, secret
func (_m *MockSecretRepo) Update(ctx context.Context, secret *models.Secret) (*models.Secret, error) {
	ret := _m.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Secret) (*models.Secret, error)); ok {
		return rf(ctx, secret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Secret) *models.Secret); ok {
		r0 = rf(ctx, secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Secret) error); ok {
		r1 = rf(ctx, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSecretRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - secret *models.Secret
func (_e *MockSecretRepo_Expecter) Update(ctx interface{}, secret interface{}) *MockSecretRepo_Update_Call {
	return &MockSecretRepo_Update_Call{Call: _e.mock.On("Update", ctx, secret)}
}

func (_c *MockSecretRepo_Update_Call) Run(run func(ctx context.Context, secret *models.Secret)) *MockSecretRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Secret))
	})
	return _c
}

func (_c *MockSecretRepo_Update_Call) Return(_a0 *models.Secret, _a1 error) *MockSecretRepo_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepo_Update_Call) RunAndReturn(run func(context.Context, *models.Secret) (*models.Secret, error)) *MockSecretRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEncryptedData provides a mock function with given fields: ctx, ownerID, secretID, encryptedData
func (_m *MockSecretRepo) UpdateEncryptedData(ctx context.Context, ownerID uuid.UUID, secretID uuid.UUID, encryptedData []byte) error {
	ret := _m.Called(ctx, ownerID, secretID, encryptedData)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEncryptedData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, []byte) error); ok {
		r0 = rf(ctx, ownerID, secretID, encryptedData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepo_UpdateEncryptedData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEncryptedData'
type MockSecretRepo_UpdateEncryptedData_Call struct {
	*mock.Call
}

// UpdateEncryptedData is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
//   - secretID uuid.UUID
//   - encryptedData []byte
func (_e *MockSecretRepo_Expecter) UpdateEncryptedData(ctx interface{}, ownerID interface{}, secretID interface{}, encryptedData interface{}) *MockSecretRepo_UpdateEncryptedData_Call {
	return &MockSecretRepo_UpdateEncryptedData_Call{Call: _e.mock.On("UpdateEncryptedData", ctx, ownerID, secretID, encryptedData)}
}

func (_c *MockSecretRepo_UpdateEncryptedData_Call) Run(run func(ctx context.Context, ownerID uuid.UUID, secretID uuid.UUID, encryptedData []byte)) *MockSecretRepo_UpdateEncryptedData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].([]byte))
	})
	return _c
}

func (_c *MockSecretRepo_UpdateEncryptedData_Call) Return(_a0 error) *MockSecretRepo_UpdateEncryptedData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepo_UpdateEncryptedData_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, []byte) error) *MockSecretRepo_UpdateEncryptedData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretRepo creates a new instance of MockSecretRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretRepo {
	mock := &MockSecretRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
