// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/onbehalfofhim/secrets-keeper/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockSerializer is an autogenerated mock type for the Serializer type
type MockSerializer struct {
	mock.Mock
}

type MockSerializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSerializer) EXPECT() *MockSerializer_Expecter {
	return &MockSerializer_Expecter{mock: &_m.Mock}
}

// Deserialize provides a mock function with given fields: secretType, data
func (_m *MockSerializer) Deserialize(secretType models.SecretType, data []byte) (interface{}, error) {
	ret := _m.Called(secretType, data)

	if len(ret) == 0 {
		panic("no return value specified for Deserialize")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(models.SecretType, []byte) (interface{}, error)); ok {
		return rf(secretType, data)
	}
	if rf, ok := ret.Get(0).(func(models.SecretType, []byte) interface{}); ok {
		r0 = rf(secretType, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(models.SecretType, []byte) error); ok {
		r1 = rf(secretType, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSerializer_Deserialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deserialize'
type MockSerializer_Deserialize_Call struct {
	*mock.Call
}

// Deserialize is a helper method to define mock.On call
//   - secretType models.SecretType
//   - data []byte
func (_e *MockSerializer_Expecter) Deserialize(secretType interface{}, data interface{}) *MockSerializer_Deserialize_Call {
	return &MockSerializer_Deserialize_Call{Call: _e.mock.On("Deserialize", secretType, data)}
}

func (_c *MockSerializer_Deserialize_Call) Run(run func(secretType models.SecretType, data []byte)) *MockSerializer_Deserialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.SecretType), args[1].([]byte))
	})
	return _c
}

func (_c *MockSerializer_Deserialize_Call) Return(_a0 interface{}, _a1 error) *MockSerializer_Deserialize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSerializer_Deserialize_Call) RunAndReturn(run func(models.SecretType, []byte) (interface{}, error)) *MockSerializer_Deserialize_Call {
	_c.Call.Return(run)
	return _c
}

// Serialize provides a mock function with given fields: data
func (_m *MockSerializer) Serialize(data interface{}) ([]byte, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) ([]byte, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func(interface{}) []byte); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSerializer_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type MockSerializer_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
//   - data interface{}
func (_e *MockSerializer_Expecter) Serialize(data interface{}) *MockSerializer_Serialize_Call {
	return &MockSerializer_Serialize_Call{Call: _e.mock.On("Serialize", data)}
}

func (_c *MockSerializer_Serialize_Call) Run(run func(data interface{})) *MockSerializer_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockSerializer_Serialize_Call) Return(_a0 []byte, _a1 error) *MockSerializer_Serialize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSerializer_Serialize_Call) RunAndReturn(run func(interface{}) ([]byte, error)) *MockSerializer_Serialize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSerializer creates a new instance of MockSerializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSerializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSerializer {
	mock := &MockSerializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
