// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: binary.proto

//go:build protoopaque

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadBinaryChunk struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretId string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3"`
	xxx_hidden_Chunk    []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UploadBinaryChunk) Reset() {
	*x = UploadBinaryChunk{}
	mi := &file_binary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBinaryChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBinaryChunk) ProtoMessage() {}

func (x *UploadBinaryChunk) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadBinaryChunk) GetSecretId() string {
	if x != nil {
		return x.xxx_hidden_SecretId
	}
	return ""
}

func (x *UploadBinaryChunk) GetChunk() []byte {
	if x != nil {
		return x.xxx_hidden_Chunk
	}
	return nil
}

func (x *UploadBinaryChunk) SetSecretId(v string) {
	x.xxx_hidden_SecretId = v
}

func (x *UploadBinaryChunk) SetChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Chunk = v
}

type UploadBinaryChunk_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretId string
	Chunk    []byte
}

func (b0 UploadBinaryChunk_builder) Build() *UploadBinaryChunk {
	m0 := &UploadBinaryChunk{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SecretId = b.SecretId
	x.xxx_hidden_Chunk = b.Chunk
	return m0
}

type UploadBinaryResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBinaryResponse) Reset() {
	*x = UploadBinaryResponse{}
	mi := &file_binary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBinaryResponse) ProtoMessage() {}

func (x *UploadBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type UploadBinaryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 UploadBinaryResponse_builder) Build() *UploadBinaryResponse {
	m0 := &UploadBinaryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DownloadBinaryRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretId string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DownloadBinaryRequest) Reset() {
	*x = DownloadBinaryRequest{}
	mi := &file_binary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBinaryRequest) ProtoMessage() {}

func (x *DownloadBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadBinaryRequest) GetSecretId() string {
	if x != nil {
		return x.xxx_hidden_SecretId
	}
	return ""
}

func (x *DownloadBinaryRequest) SetSecretId(v string) {
	x.xxx_hidden_SecretId = v
}

type DownloadBinaryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretId string
}

func (b0 DownloadBinaryRequest_builder) Build() *DownloadBinaryRequest {
	m0 := &DownloadBinaryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SecretId = b.SecretId
	return m0
}

type DownloadBinaryChunk struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Chunk []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DownloadBinaryChunk) Reset() {
	*x = DownloadBinaryChunk{}
	mi := &file_binary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBinaryChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBinaryChunk) ProtoMessage() {}

func (x *DownloadBinaryChunk) ProtoReflect() protoreflect.Message {
	mi := &file_binary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadBinaryChunk) GetChunk() []byte {
	if x != nil {
		return x.xxx_hidden_Chunk
	}
	return nil
}

func (x *DownloadBinaryChunk) SetChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Chunk = v
}

type DownloadBinaryChunk_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Chunk []byte
}

func (b0 DownloadBinaryChunk_builder) Build() *DownloadBinaryChunk {
	m0 := &DownloadBinaryChunk{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Chunk = b.Chunk
	return m0
}

var File_binary_proto protoreflect.FileDescriptor

const file_binary_proto_rawDesc = "" +
	"\n" +
	"\fbinary.proto\x12\x0fsecretkeeper.v1\"F\n" +
	"\x11UploadBinaryChunk\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\"\x16\n" +
	"\x14UploadBinaryResponse\"4\n" +
	"\x15DownloadBinaryRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\"+\n" +
	"\x13DownloadBinaryChunk\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2\xce\x01\n" +
	"\rBinaryService\x12[\n" +
	"\fUploadBinary\x12\".secretkeeper.v1.UploadBinaryChunk\x1a%.secretkeeper.v1.UploadBinaryResponse(\x01\x12`\n" +
	"\x0eDownloadBinary\x12&.secretkeeper.v1.DownloadBinaryRequest\x1a$.secretkeeper.v1.DownloadBinaryChunk0\x01B3Z1github.com/onbehalfofhim/secrets-keeper/api/protob\x06proto3"

var file_binary_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_binary_proto_goTypes = []any{
	(*UploadBinaryChunk)(nil),     // 0: secretkeeper.v1.UploadBinaryChunk
	(*UploadBinaryResponse)(nil),  // 1: secretkeeper.v1.UploadBinaryResponse
	(*DownloadBinaryRequest)(nil), // 2: secretkeeper.v1.DownloadBinaryRequest
	(*DownloadBinaryChunk)(nil),   // 3: secretkeeper.v1.DownloadBinaryChunk
}
var file_binary_proto_depIdxs = []int32{
	0, // 0: secretkeeper.v1.BinaryService.UploadBinary:input_type -> secretkeeper.v1.UploadBinaryChunk
	2, // 1: secretkeeper.v1.BinaryService.DownloadBinary:input_type -> secretkeeper.v1.DownloadBinaryRequest
	1, // 2: secretkeeper.v1.BinaryService.UploadBinary:output_type -> secretkeeper.v1.UploadBinaryResponse
	3, // 3: secretkeeper.v1.BinaryService.DownloadBinary:output_type -> secretkeeper.v1.DownloadBinaryChunk
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_binary_proto_init() }
func file_binary_proto_init() {
	if File_binary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_binary_proto_rawDesc), len(file_binary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_binary_proto_goTypes,
		DependencyIndexes: file_binary_proto_depIdxs,
		MessageInfos:      file_binary_proto_msgTypes,
	}.Build()
	File_binary_proto = out.File
	file_binary_proto_goTypes = nil
	file_binary_proto_depIdxs = nil
}
