// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: binary.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BinaryService_UploadBinary_FullMethodName   = "/secretkeeper.v1.BinaryService/UploadBinary"
	BinaryService_DownloadBinary_FullMethodName = "/secretkeeper.v1.BinaryService/DownloadBinary"
)

// BinaryServiceClient is the client API for BinaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BinaryServiceClient interface {
	UploadBinary(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadBinaryChunk, UploadBinaryResponse], error)
	DownloadBinary(ctx context.Context, in *DownloadBinaryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadBinaryChunk], error)
}

type binaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBinaryServiceClient(cc grpc.ClientConnInterface) BinaryServiceClient {
	return &binaryServiceClient{cc}
}

func (c *binaryServiceClient) UploadBinary(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadBinaryChunk, UploadBinaryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BinaryService_ServiceDesc.Streams[0], BinaryService_UploadBinary_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadBinaryChunk, UploadBinaryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BinaryService_UploadBinaryClient = grpc.ClientStreamingClient[UploadBinaryChunk, UploadBinaryResponse]

func (c *binaryServiceClient) DownloadBinary(ctx context.Context, in *DownloadBinaryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadBinaryChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BinaryService_ServiceDesc.Streams[1], BinaryService_DownloadBinary_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadBinaryRequest, DownloadBinaryChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BinaryService_DownloadBinaryClient = grpc.ServerStreamingClient[DownloadBinaryChunk]

// BinaryServiceServer is the server API for BinaryService service.
// All implementations must embed UnimplementedBinaryServiceServer
// for forward compatibility.
type BinaryServiceServer interface {
	UploadBinary(grpc.ClientStreamingServer[UploadBinaryChunk, UploadBinaryResponse]) error
	DownloadBinary(*DownloadBinaryRequest, grpc.ServerStreamingServer[DownloadBinaryChunk]) error
	mustEmbedUnimplementedBinaryServiceServer()
}

// UnimplementedBinaryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBinaryServiceServer struct{}

func (UnimplementedBinaryServiceServer) UploadBinary(grpc.ClientStreamingServer[UploadBinaryChunk, UploadBinaryResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadBinary not implemented")
}
func (UnimplementedBinaryServiceServer) DownloadBinary(*DownloadBinaryRequest, grpc.ServerStreamingServer[DownloadBinaryChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadBinary not implemented")
}
func (UnimplementedBinaryServiceServer) mustEmbedUnimplementedBinaryServiceServer() {}
func (UnimplementedBinaryServiceServer) testEmbeddedByValue()                       {}

// UnsafeBinaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BinaryServiceServer will
// result in compilation errors.
type UnsafeBinaryServiceServer interface {
	mustEmbedUnimplementedBinaryServiceServer()
}

func RegisterBinaryServiceServer(s grpc.ServiceRegistrar, srv BinaryServiceServer) {
	// If the following call panics, it indicates UnimplementedBinaryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BinaryService_ServiceDesc, srv)
}

func _BinaryService_UploadBinary_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BinaryServiceServer).UploadBinary(&grpc.GenericServerStream[UploadBinaryChunk, UploadBinaryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BinaryService_UploadBinaryServer = grpc.ClientStreamingServer[UploadBinaryChunk, UploadBinaryResponse]

func _BinaryService_DownloadBinary_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadBinaryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BinaryServiceServer).DownloadBinary(m, &grpc.GenericServerStream[DownloadBinaryRequest, DownloadBinaryChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BinaryService_DownloadBinaryServer = grpc.ServerStreamingServer[DownloadBinaryChunk]

// BinaryService_ServiceDesc is the grpc.ServiceDesc for BinaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BinaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secretkeeper.v1.BinaryService",
	HandlerType: (*BinaryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadBinary",
			Handler:       _BinaryService_UploadBinary_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadBinary",
			Handler:       _BinaryService_DownloadBinary_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "binary.proto",
}
