// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: common.proto

//go:build protoopaque

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretType int32

const (
	SecretType_SECRET_TYPE_UNSPECIFIED    SecretType = 0
	SecretType_SECRET_TYPE_TEXT           SecretType = 1
	SecretType_SECRET_TYPE_LOGIN_PASSWORD SecretType = 2
	SecretType_SECRET_TYPE_BANK_CARD      SecretType = 3
	SecretType_SECRET_TYPE_BINARY_FILE    SecretType = 4
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "SECRET_TYPE_UNSPECIFIED",
		1: "SECRET_TYPE_TEXT",
		2: "SECRET_TYPE_LOGIN_PASSWORD",
		3: "SECRET_TYPE_BANK_CARD",
		4: "SECRET_TYPE_BINARY_FILE",
	}
	SecretType_value = map[string]int32{
		"SECRET_TYPE_UNSPECIFIED":    0,
		"SECRET_TYPE_TEXT":           1,
		"SECRET_TYPE_LOGIN_PASSWORD": 2,
		"SECRET_TYPE_BANK_CARD":      3,
		"SECRET_TYPE_BINARY_FILE":    4,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SecretMetadata struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Type        SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=secretkeeper.v1.SecretType"`
	xxx_hidden_Title       string                 `protobuf:"bytes,3,opt,name=title,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,4,opt,name=description,proto3"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretMetadata) Reset() {
	*x = SecretMetadata{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretMetadata) ProtoMessage() {}

func (x *SecretMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretMetadata) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *SecretMetadata) GetType() SecretType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *SecretMetadata) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *SecretMetadata) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *SecretMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *SecretMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *SecretMetadata) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *SecretMetadata) SetType(v SecretType) {
	x.xxx_hidden_Type = v
}

func (x *SecretMetadata) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *SecretMetadata) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *SecretMetadata) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *SecretMetadata) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *SecretMetadata) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *SecretMetadata) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *SecretMetadata) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *SecretMetadata) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type SecretMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          string
	Type        SecretType
	Title       string
	Description string
	CreatedAt   *timestamppb.Timestamp
	UpdatedAt   *timestamppb.Timestamp
}

func (b0 SecretMetadata_builder) Build() *SecretMetadata {
	m0 := &SecretMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x0fsecretkeeper.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x01\n" +
	"\x0eSecretMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.secretkeeper.v1.SecretTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\x97\x01\n" +
	"\n" +
	"SecretType\x12\x1b\n" +
	"\x17SECRET_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SECRET_TYPE_TEXT\x10\x01\x12\x1e\n" +
	"\x1aSECRET_TYPE_LOGIN_PASSWORD\x10\x02\x12\x19\n" +
	"\x15SECRET_TYPE_BANK_CARD\x10\x03\x12\x1b\n" +
	"\x17SECRET_TYPE_BINARY_FILE\x10\x04B3Z1github.com/onbehalfofhim/secrets-keeper/api/protob\x06proto3"

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_goTypes = []any{
	(SecretType)(0),               // 0: secretkeeper.v1.SecretType
	(*SecretMetadata)(nil),        // 1: secretkeeper.v1.SecretMetadata
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	0, // 0: secretkeeper.v1.SecretMetadata.type:type_name -> secretkeeper.v1.SecretType
	2, // 1: secretkeeper.v1.SecretMetadata.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: secretkeeper.v1.SecretMetadata.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
