syntax = "proto3";

package secretkeeper.v1;

option go_package = "github.com/onbehalfofhim/secrets-keeper/api/proto";

import "common.proto";

service SecretService {
    rpc CreateSecret(CreateSecretRequest) returns (CreateSecretResponse);
    rpc UpdateSecret(UpdateSecretRequest) returns (UpdateSecretResponse);
    rpc DeleteSecret(DeleteSecretRequest) returns (DeleteSecretResponse);

    rpc GetSecret(GetSecretRequest) returns (GetSecretResponse);
    rpc ListSecrets(ListSecretsRequest) returns (ListSecretsResponse);
}

message Secret {
    SecretMetadata metadata = 1;

    oneof payload {
        TextSecret text = 10;
        LoginPasswordSecret login_password = 11;
        BankCardSecret bank_card = 12;
        BinarySecret binary = 13;
    }
}

message TextSecret {
    string text = 1;
}

message LoginPasswordSecret {
    string login = 1;
    string password = 2;
}

message BankCardSecret {
    string number = 1;
    string holder = 2;
    string expire = 3;
    string cvv = 4;
}

message BinarySecret {
    string filename = 1;
    string mime_type = 2;
}

message CreateSecretRequest {
    Secret secret = 1;
}

message CreateSecretResponse {
    string id = 1;
}

message UpdateSecretRequest {
    Secret secret = 1;
}

message UpdateSecretResponse {}

message DeleteSecretRequest {
    string id = 1;
}

message DeleteSecretResponse {}

message GetSecretRequest {
    string id = 1;
}

message GetSecretResponse {
    Secret secret = 1;
}

message ListSecretsRequest {}

message ListSecretsResponse {
    repeated SecretMetadata secrets = 1;
}