// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: secret.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Secret struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *SecretMetadata        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Secret_Text
	//	*Secret_LoginPassword
	//	*Secret_BankCard
	//	*Secret_Binary
	Payload       isSecret_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{0}
}

func (x *Secret) GetMetadata() *SecretMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Secret) GetPayload() isSecret_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Secret) GetText() *TextSecret {
	if x != nil {
		if x, ok := x.Payload.(*Secret_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Secret) GetLoginPassword() *LoginPasswordSecret {
	if x != nil {
		if x, ok := x.Payload.(*Secret_LoginPassword); ok {
			return x.LoginPassword
		}
	}
	return nil
}

func (x *Secret) GetBankCard() *BankCardSecret {
	if x != nil {
		if x, ok := x.Payload.(*Secret_BankCard); ok {
			return x.BankCard
		}
	}
	return nil
}

func (x *Secret) GetBinary() *BinarySecret {
	if x != nil {
		if x, ok := x.Payload.(*Secret_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

type isSecret_Payload interface {
	isSecret_Payload()
}

type Secret_Text struct {
	Text *TextSecret `protobuf:"bytes,10,opt,name=text,proto3,oneof"`
}

type Secret_LoginPassword struct {
	LoginPassword *LoginPasswordSecret `protobuf:"bytes,11,opt,name=login_password,json=loginPassword,proto3,oneof"`
}

type Secret_BankCard struct {
	BankCard *BankCardSecret `protobuf:"bytes,12,opt,name=bank_card,json=bankCard,proto3,oneof"`
}

type Secret_Binary struct {
	Binary *BinarySecret `protobuf:"bytes,13,opt,name=binary,proto3,oneof"`
}

func (*Secret_Text) isSecret_Payload() {}

func (*Secret_LoginPassword) isSecret_Payload() {}

func (*Secret_BankCard) isSecret_Payload() {}

func (*Secret_Binary) isSecret_Payload() {}

type TextSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextSecret) Reset() {
	*x = TextSecret{}
	mi := &file_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSecret) ProtoMessage() {}

func (x *TextSecret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextSecret.ProtoReflect.Descriptor instead.
func (*TextSecret) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{1}
}

func (x *TextSecret) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LoginPasswordSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginPasswordSecret) Reset() {
	*x = LoginPasswordSecret{}
	mi := &file_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginPasswordSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPasswordSecret) ProtoMessage() {}

func (x *LoginPasswordSecret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginPasswordSecret.ProtoReflect.Descriptor instead.
func (*LoginPasswordSecret) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{2}
}

func (x *LoginPasswordSecret) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginPasswordSecret) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BankCardSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Holder        string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	Expire        string                 `protobuf:"bytes,3,opt,name=expire,proto3" json:"expire,omitempty"`
	Cvv           string                 `protobuf:"bytes,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCardSecret) Reset() {
	*x = BankCardSecret{}
	mi := &file_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCardSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCardSecret) ProtoMessage() {}

func (x *BankCardSecret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCardSecret.ProtoReflect.Descriptor instead.
func (*BankCardSecret) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{3}
}

func (x *BankCardSecret) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *BankCardSecret) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *BankCardSecret) GetExpire() string {
	if x != nil {
		return x.Expire
	}
	return ""
}

func (x *BankCardSecret) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

type BinarySecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinarySecret) Reset() {
	*x = BinarySecret{}
	mi := &file_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinarySecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinarySecret) ProtoMessage() {}

func (x *BinarySecret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinarySecret.ProtoReflect.Descriptor instead.
func (*BinarySecret) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{4}
}

func (x *BinarySecret) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *BinarySecret) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type CreateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_secret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSecretRequest) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_secret_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSecretResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_secret_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSecretRequest) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type UpdateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_secret_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{8}
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_secret_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_secret_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{10}
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_secret_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{11}
}

func (x *GetSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_secret_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{12}
}

func (x *GetSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_secret_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{13}
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretMetadata      `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_secret_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{14}
}

func (x *ListSecretsResponse) GetSecrets() []*SecretMetadata {
	if x != nil {
		return x.Secrets
	}
	return nil
}

var File_secret_proto protoreflect.FileDescriptor

const file_secret_proto_rawDesc = "" +
	"\n" +
	"\fsecret.proto\x12\x0fsecretkeeper.v1\x1a\fcommon.proto\"\xcb\x02\n" +
	"\x06Secret\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.secretkeeper.v1.SecretMetadataR\bmetadata\x121\n" +
	"\x04text\x18\n" +
	" \x01(\v2\x1b.secretkeeper.v1.TextSecretH\x00R\x04text\x12M\n" +
	"\x0elogin_password\x18\v \x01(\v2$.secretkeeper.v1.LoginPasswordSecretH\x00R\rloginPassword\x12>\n" +
	"\tbank_card\x18\f \x01(\v2\x1f.secretkeeper.v1.BankCardSecretH\x00R\bbankCard\x127\n" +
	"\x06binary\x18\r \x01(\v2\x1d.secretkeeper.v1.BinarySecretH\x00R\x06binaryB\t\n" +
	"\apayload\" \n" +
	"\n" +
	"TextSecret\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"G\n" +
	"\x13LoginPasswordSecret\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"j\n" +
	"\x0eBankCardSecret\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x16\n" +
	"\x06expire\x18\x03 \x01(\tR\x06expire\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\"G\n" +
	"\fBinarySecret\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"F\n" +
	"\x13CreateSecretRequest\x12/\n" +
	"\x06secret\x18\x01 \x01(\v2\x17.secretkeeper.v1.SecretR\x06secret\"&\n" +
	"\x14CreateSecretResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x13UpdateSecretRequest\x12/\n" +
	"\x06secret\x18\x01 \x01(\v2\x17.secretkeeper.v1.SecretR\x06secret\"\x16\n" +
	"\x14UpdateSecretResponse\"%\n" +
	"\x13DeleteSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteSecretResponse\"\"\n" +
	"\x10GetSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x11GetSecretResponse\x12/\n" +
	"\x06secret\x18\x01 \x01(\v2\x17.secretkeeper.v1.SecretR\x06secret\"\x14\n" +
	"\x12ListSecretsRequest\"P\n" +
	"\x13ListSecretsResponse\x129\n" +
	"\asecrets\x18\x01 \x03(\v2\x1f.secretkeeper.v1.SecretMetadataR\asecrets2\xd4\x03\n" +
	"\rSecretService\x12[\n" +
	"\fCreateSecret\x12$.secretkeeper.v1.CreateSecretRequest\x1a%.secretkeeper.v1.CreateSecretResponse\x12[\n" +
	"\fUpdateSecret\x12$.secretkeeper.v1.UpdateSecretRequest\x1a%.secretkeeper.v1.UpdateSecretResponse\x12[\n" +
	"\fDeleteSecret\x12$.secretkeeper.v1.DeleteSecretRequest\x1a%.secretkeeper.v1.DeleteSecretResponse\x12R\n" +
	"\tGetSecret\x12!.secretkeeper.v1.GetSecretRequest\x1a\".secretkeeper.v1.GetSecretResponse\x12X\n" +
	"\vListSecrets\x12#.secretkeeper.v1.ListSecretsRequest\x1a$.secretkeeper.v1.ListSecretsResponseB3Z1github.com/onbehalfofhim/secrets-keeper/api/protob\x06proto3"

var (
	file_secret_proto_rawDescOnce sync.Once
	file_secret_proto_rawDescData []byte
)

func file_secret_proto_rawDescGZIP() []byte {
	file_secret_proto_rawDescOnce.Do(func() {
		file_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secret_proto_rawDesc), len(file_secret_proto_rawDesc)))
	})
	return file_secret_proto_rawDescData
}

var file_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_secret_proto_goTypes = []any{
	(*Secret)(nil),               // 0: secretkeeper.v1.Secret
	(*TextSecret)(nil),           // 1: secretkeeper.v1.TextSecret
	(*LoginPasswordSecret)(nil),  // 2: secretkeeper.v1.LoginPasswordSecret
	(*BankCardSecret)(nil),       // 3: secretkeeper.v1.BankCardSecret
	(*BinarySecret)(nil),         // 4: secretkeeper.v1.BinarySecret
	(*CreateSecretRequest)(nil),  // 5: secretkeeper.v1.CreateSecretRequest
	(*CreateSecretResponse)(nil), // 6: secretkeeper.v1.CreateSecretResponse
	(*UpdateSecretRequest)(nil),  // 7: secretkeeper.v1.UpdateSecretRequest
	(*UpdateSecretResponse)(nil), // 8: secretkeeper.v1.UpdateSecretResponse
	(*DeleteSecretRequest)(nil),  // 9: secretkeeper.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil), // 10: secretkeeper.v1.DeleteSecretResponse
	(*GetSecretRequest)(nil),     // 11: secretkeeper.v1.GetSecretRequest
	(*GetSecretResponse)(nil),    // 12: secretkeeper.v1.GetSecretResponse
	(*ListSecretsRequest)(nil),   // 13: secretkeeper.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),  // 14: secretkeeper.v1.ListSecretsResponse
	(*SecretMetadata)(nil),       // 15: secretkeeper.v1.SecretMetadata
}
var file_secret_proto_depIdxs = []int32{
	15, // 0: secretkeeper.v1.Secret.metadata:type_name -> secretkeeper.v1.SecretMetadata
	1,  // 1: secretkeeper.v1.Secret.text:type_name -> secretkeeper.v1.TextSecret
	2,  // 2: secretkeeper.v1.Secret.login_password:type_name -> secretkeeper.v1.LoginPasswordSecret
	3,  // 3: secretkeeper.v1.Secret.bank_card:type_name -> secretkeeper.v1.BankCardSecret
	4,  // 4: secretkeeper.v1.Secret.binary:type_name -> secretkeeper.v1.BinarySecret
	0,  // 5: secretkeeper.v1.CreateSecretRequest.secret:type_name -> secretkeeper.v1.Secret
	0,  // 6: secretkeeper.v1.UpdateSecretRequest.secret:type_name -> secretkeeper.v1.Secret
	0,  // 7: secretkeeper.v1.GetSecretResponse.secret:type_name -> secretkeeper.v1.Secret
	15, // 8: secretkeeper.v1.ListSecretsResponse.secrets:type_name -> secretkeeper.v1.SecretMetadata
	5,  // 9: secretkeeper.v1.SecretService.CreateSecret:input_type -> secretkeeper.v1.CreateSecretRequest
	7,  // 10: secretkeeper.v1.SecretService.UpdateSecret:input_type -> secretkeeper.v1.UpdateSecretRequest
	9,  // 11: secretkeeper.v1.SecretService.DeleteSecret:input_type -> secretkeeper.v1.DeleteSecretRequest
	11, // 12: secretkeeper.v1.SecretService.GetSecret:input_type -> secretkeeper.v1.GetSecretRequest
	13, // 13: secretkeeper.v1.SecretService.ListSecrets:input_type -> secretkeeper.v1.ListSecretsRequest
	6,  // 14: secretkeeper.v1.SecretService.CreateSecret:output_type -> secretkeeper.v1.CreateSecretResponse
	8,  // 15: secretkeeper.v1.SecretService.UpdateSecret:output_type -> secretkeeper.v1.UpdateSecretResponse
	10, // 16: secretkeeper.v1.SecretService.DeleteSecret:output_type -> secretkeeper.v1.DeleteSecretResponse
	12, // 17: secretkeeper.v1.SecretService.GetSecret:output_type -> secretkeeper.v1.GetSecretResponse
	14, // 18: secretkeeper.v1.SecretService.ListSecrets:output_type -> secretkeeper.v1.ListSecretsResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_secret_proto_init() }
func file_secret_proto_init() {
	if File_secret_proto != nil {
		return
	}
	file_common_proto_init()
	file_secret_proto_msgTypes[0].OneofWrappers = []any{
		(*Secret_Text)(nil),
		(*Secret_LoginPassword)(nil),
		(*Secret_BankCard)(nil),
		(*Secret_Binary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secret_proto_rawDesc), len(file_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secret_proto_goTypes,
		DependencyIndexes: file_secret_proto_depIdxs,
		MessageInfos:      file_secret_proto_msgTypes,
	}.Build()
	File_secret_proto = out.File
	file_secret_proto_goTypes = nil
	file_secret_proto_depIdxs = nil
}
