// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: secret.proto

//go:build protoopaque

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Secret struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *SecretMetadata        `protobuf:"bytes,1,opt,name=metadata,proto3"`
	xxx_hidden_Payload  isSecret_Payload       `protobuf_oneof:"payload"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Secret) GetMetadata() *SecretMetadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Secret) GetText() *TextSecret {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*secret_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Secret) GetLoginPassword() *LoginPasswordSecret {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*secret_LoginPassword); ok {
			return x.LoginPassword
		}
	}
	return nil
}

func (x *Secret) GetBankCard() *BankCardSecret {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*secret_BankCard); ok {
			return x.BankCard
		}
	}
	return nil
}

func (x *Secret) GetBinary() *BinarySecret {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*secret_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

func (x *Secret) SetMetadata(v *SecretMetadata) {
	x.xxx_hidden_Metadata = v
}

func (x *Secret) SetText(v *TextSecret) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &secret_Text{v}
}

func (x *Secret) SetLoginPassword(v *LoginPasswordSecret) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &secret_LoginPassword{v}
}

func (x *Secret) SetBankCard(v *BankCardSecret) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &secret_BankCard{v}
}

func (x *Secret) SetBinary(v *BinarySecret) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &secret_Binary{v}
}

func (x *Secret) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *Secret) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *Secret) HasText() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*secret_Text)
	return ok
}

func (x *Secret) HasLoginPassword() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*secret_LoginPassword)
	return ok
}

func (x *Secret) HasBankCard() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*secret_BankCard)
	return ok
}

func (x *Secret) HasBinary() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*secret_Binary)
	return ok
}

func (x *Secret) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *Secret) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *Secret) ClearText() {
	if _, ok := x.xxx_hidden_Payload.(*secret_Text); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *Secret) ClearLoginPassword() {
	if _, ok := x.xxx_hidden_Payload.(*secret_LoginPassword); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *Secret) ClearBankCard() {
	if _, ok := x.xxx_hidden_Payload.(*secret_BankCard); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *Secret) ClearBinary() {
	if _, ok := x.xxx_hidden_Payload.(*secret_Binary); ok {
		x.xxx_hidden_Payload = nil
	}
}

const Secret_Payload_not_set_case case_Secret_Payload = 0
const Secret_Text_case case_Secret_Payload = 10
const Secret_LoginPassword_case case_Secret_Payload = 11
const Secret_BankCard_case case_Secret_Payload = 12
const Secret_Binary_case case_Secret_Payload = 13

func (x *Secret) WhichPayload() case_Secret_Payload {
	if x == nil {
		return Secret_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *secret_Text:
		return Secret_Text_case
	case *secret_LoginPassword:
		return Secret_LoginPassword_case
	case *secret_BankCard:
		return Secret_BankCard_case
	case *secret_Binary:
		return Secret_Binary_case
	default:
		return Secret_Payload_not_set_case
	}
}

type Secret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *SecretMetadata
	// Fields of oneof xxx_hidden_Payload:
	Text          *TextSecret
	LoginPassword *LoginPasswordSecret
	BankCard      *BankCardSecret
	Binary        *BinarySecret
	// -- end of xxx_hidden_Payload
}

func (b0 Secret_builder) Build() *Secret {
	m0 := &Secret{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	if b.Text != nil {
		x.xxx_hidden_Payload = &secret_Text{b.Text}
	}
	if b.LoginPassword != nil {
		x.xxx_hidden_Payload = &secret_LoginPassword{b.LoginPassword}
	}
	if b.BankCard != nil {
		x.xxx_hidden_Payload = &secret_BankCard{b.BankCard}
	}
	if b.Binary != nil {
		x.xxx_hidden_Payload = &secret_Binary{b.Binary}
	}
	return m0
}

type case_Secret_Payload protoreflect.FieldNumber

func (x case_Secret_Payload) String() string {
	md := file_secret_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSecret_Payload interface {
	isSecret_Payload()
}

type secret_Text struct {
	Text *TextSecret `protobuf:"bytes,10,opt,name=text,proto3,oneof"`
}

type secret_LoginPassword struct {
	LoginPassword *LoginPasswordSecret `protobuf:"bytes,11,opt,name=login_password,json=loginPassword,proto3,oneof"`
}

type secret_BankCard struct {
	BankCard *BankCardSecret `protobuf:"bytes,12,opt,name=bank_card,json=bankCard,proto3,oneof"`
}

type secret_Binary struct {
	Binary *BinarySecret `protobuf:"bytes,13,opt,name=binary,proto3,oneof"`
}

func (*secret_Text) isSecret_Payload() {}

func (*secret_LoginPassword) isSecret_Payload() {}

func (*secret_BankCard) isSecret_Payload() {}

func (*secret_Binary) isSecret_Payload() {}

type TextSecret struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Text string                 `protobuf:"bytes,1,opt,name=text,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TextSecret) Reset() {
	*x = TextSecret{}
	mi := &file_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSecret) ProtoMessage() {}

func (x *TextSecret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TextSecret) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *TextSecret) SetText(v string) {
	x.xxx_hidden_Text = v
}

type TextSecret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Text string
}

func (b0 TextSecret_builder) Build() *TextSecret {
	m0 := &TextSecret{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Text = b.Text
	return m0
}

type LoginPasswordSecret struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login    string                 `protobuf:"bytes,1,opt,name=login,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoginPasswordSecret) Reset() {
	*x = LoginPasswordSecret{}
	mi := &file_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginPasswordSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPasswordSecret) ProtoMessage() {}

func (x *LoginPasswordSecret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginPasswordSecret) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *LoginPasswordSecret) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *LoginPasswordSecret) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *LoginPasswordSecret) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

type LoginPasswordSecret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    string
	Password string
}

func (b0 LoginPasswordSecret_builder) Build() *LoginPasswordSecret {
	m0 := &LoginPasswordSecret{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	return m0
}

type BankCardSecret struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number string                 `protobuf:"bytes,1,opt,name=number,proto3"`
	xxx_hidden_Holder string                 `protobuf:"bytes,2,opt,name=holder,proto3"`
	xxx_hidden_Expire string                 `protobuf:"bytes,3,opt,name=expire,proto3"`
	xxx_hidden_Cvv    string                 `protobuf:"bytes,4,opt,name=cvv,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BankCardSecret) Reset() {
	*x = BankCardSecret{}
	mi := &file_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCardSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCardSecret) ProtoMessage() {}

func (x *BankCardSecret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BankCardSecret) GetNumber() string {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return ""
}

func (x *BankCardSecret) GetHolder() string {
	if x != nil {
		return x.xxx_hidden_Holder
	}
	return ""
}

func (x *BankCardSecret) GetExpire() string {
	if x != nil {
		return x.xxx_hidden_Expire
	}
	return ""
}

func (x *BankCardSecret) GetCvv() string {
	if x != nil {
		return x.xxx_hidden_Cvv
	}
	return ""
}

func (x *BankCardSecret) SetNumber(v string) {
	x.xxx_hidden_Number = v
}

func (x *BankCardSecret) SetHolder(v string) {
	x.xxx_hidden_Holder = v
}

func (x *BankCardSecret) SetExpire(v string) {
	x.xxx_hidden_Expire = v
}

func (x *BankCardSecret) SetCvv(v string) {
	x.xxx_hidden_Cvv = v
}

type BankCardSecret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number string
	Holder string
	Expire string
	Cvv    string
}

func (b0 BankCardSecret_builder) Build() *BankCardSecret {
	m0 := &BankCardSecret{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Number = b.Number
	x.xxx_hidden_Holder = b.Holder
	x.xxx_hidden_Expire = b.Expire
	x.xxx_hidden_Cvv = b.Cvv
	return m0
}

type BinarySecret struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filename string                 `protobuf:"bytes,1,opt,name=filename,proto3"`
	xxx_hidden_MimeType string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BinarySecret) Reset() {
	*x = BinarySecret{}
	mi := &file_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinarySecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinarySecret) ProtoMessage() {}

func (x *BinarySecret) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BinarySecret) GetFilename() string {
	if x != nil {
		return x.xxx_hidden_Filename
	}
	return ""
}

func (x *BinarySecret) GetMimeType() string {
	if x != nil {
		return x.xxx_hidden_MimeType
	}
	return ""
}

func (x *BinarySecret) SetFilename(v string) {
	x.xxx_hidden_Filename = v
}

func (x *BinarySecret) SetMimeType(v string) {
	x.xxx_hidden_MimeType = v
}

type BinarySecret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Filename string
	MimeType string
}

func (b0 BinarySecret_builder) Build() *BinarySecret {
	m0 := &BinarySecret{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filename = b.Filename
	x.xxx_hidden_MimeType = b.MimeType
	return m0
}

type CreateSecretRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secret *Secret                `protobuf:"bytes,1,opt,name=secret,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_secret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSecretRequest) GetSecret() *Secret {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *CreateSecretRequest) SetSecret(v *Secret) {
	x.xxx_hidden_Secret = v
}

func (x *CreateSecretRequest) HasSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Secret != nil
}

func (x *CreateSecretRequest) ClearSecret() {
	x.xxx_hidden_Secret = nil
}

type CreateSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secret *Secret
}

func (b0 CreateSecretRequest_builder) Build() *CreateSecretRequest {
	m0 := &CreateSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_secret_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSecretResponse) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *CreateSecretResponse) SetId(v string) {
	x.xxx_hidden_Id = v
}

type CreateSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 CreateSecretResponse_builder) Build() *CreateSecretResponse {
	m0 := &CreateSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type UpdateSecretRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secret *Secret                `protobuf:"bytes,1,opt,name=secret,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_secret_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateSecretRequest) GetSecret() *Secret {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *UpdateSecretRequest) SetSecret(v *Secret) {
	x.xxx_hidden_Secret = v
}

func (x *UpdateSecretRequest) HasSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Secret != nil
}

func (x *UpdateSecretRequest) ClearSecret() {
	x.xxx_hidden_Secret = nil
}

type UpdateSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secret *Secret
}

func (b0 UpdateSecretRequest_builder) Build() *UpdateSecretRequest {
	m0 := &UpdateSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type UpdateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_secret_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type UpdateSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 UpdateSecretResponse_builder) Build() *UpdateSecretResponse {
	m0 := &UpdateSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_secret_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSecretRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *DeleteSecretRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

type DeleteSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 DeleteSecretRequest_builder) Build() *DeleteSecretRequest {
	m0 := &DeleteSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_secret_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteSecretResponse_builder) Build() *DeleteSecretResponse {
	m0 := &DeleteSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_secret_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *GetSecretRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

type GetSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 GetSecretRequest_builder) Build() *GetSecretRequest {
	m0 := &GetSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type GetSecretResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secret *Secret                `protobuf:"bytes,1,opt,name=secret,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_secret_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *GetSecretResponse) SetSecret(v *Secret) {
	x.xxx_hidden_Secret = v
}

func (x *GetSecretResponse) HasSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Secret != nil
}

func (x *GetSecretResponse) ClearSecret() {
	x.xxx_hidden_Secret = nil
}

type GetSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secret *Secret
}

func (b0 GetSecretResponse_builder) Build() *GetSecretResponse {
	m0 := &GetSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_secret_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListSecretsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListSecretsRequest_builder) Build() *ListSecretsRequest {
	m0 := &ListSecretsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListSecretsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secrets *[]*SecretMetadata     `protobuf:"bytes,1,rep,name=secrets,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_secret_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListSecretsResponse) GetSecrets() []*SecretMetadata {
	if x != nil {
		if x.xxx_hidden_Secrets != nil {
			return *x.xxx_hidden_Secrets
		}
	}
	return nil
}

func (x *ListSecretsResponse) SetSecrets(v []*SecretMetadata) {
	x.xxx_hidden_Secrets = &v
}

type ListSecretsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secrets []*SecretMetadata
}

func (b0 ListSecretsResponse_builder) Build() *ListSecretsResponse {
	m0 := &ListSecretsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secrets = &b.Secrets
	return m0
}

var File_secret_proto protoreflect.FileDescriptor

const file_secret_proto_rawDesc = "" +
	"\n" +
	"\fsecret.proto\x12\x0fsecretkeeper.v1\x1a\fcommon.proto\"\xcb\x02\n" +
	"\x06Secret\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.secretkeeper.v1.SecretMetadataR\bmetadata\x121\n" +
	"\x04text\x18\n" +
	" \x01(\v2\x1b.secretkeeper.v1.TextSecretH\x00R\x04text\x12M\n" +
	"\x0elogin_password\x18\v \x01(\v2$.secretkeeper.v1.LoginPasswordSecretH\x00R\rloginPassword\x12>\n" +
	"\tbank_card\x18\f \x01(\v2\x1f.secretkeeper.v1.BankCardSecretH\x00R\bbankCard\x127\n" +
	"\x06binary\x18\r \x01(\v2\x1d.secretkeeper.v1.BinarySecretH\x00R\x06binaryB\t\n" +
	"\apayload\" \n" +
	"\n" +
	"TextSecret\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"G\n" +
	"\x13LoginPasswordSecret\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"j\n" +
	"\x0eBankCardSecret\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x16\n" +
	"\x06expire\x18\x03 \x01(\tR\x06expire\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\"G\n" +
	"\fBinarySecret\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"F\n" +
	"\x13CreateSecretRequest\x12/\n" +
	"\x06secret\x18\x01 \x01(\v2\x17.secretkeeper.v1.SecretR\x06secret\"&\n" +
	"\x14CreateSecretResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x13UpdateSecretRequest\x12/\n" +
	"\x06secret\x18\x01 \x01(\v2\x17.secretkeeper.v1.SecretR\x06secret\"\x16\n" +
	"\x14UpdateSecretResponse\"%\n" +
	"\x13DeleteSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteSecretResponse\"\"\n" +
	"\x10GetSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x11GetSecretResponse\x12/\n" +
	"\x06secret\x18\x01 \x01(\v2\x17.secretkeeper.v1.SecretR\x06secret\"\x14\n" +
	"\x12ListSecretsRequest\"P\n" +
	"\x13ListSecretsResponse\x129\n" +
	"\asecrets\x18\x01 \x03(\v2\x1f.secretkeeper.v1.SecretMetadataR\asecrets2\xd4\x03\n" +
	"\rSecretService\x12[\n" +
	"\fCreateSecret\x12$.secretkeeper.v1.CreateSecretRequest\x1a%.secretkeeper.v1.CreateSecretResponse\x12[\n" +
	"\fUpdateSecret\x12$.secretkeeper.v1.UpdateSecretRequest\x1a%.secretkeeper.v1.UpdateSecretResponse\x12[\n" +
	"\fDeleteSecret\x12$.secretkeeper.v1.DeleteSecretRequest\x1a%.secretkeeper.v1.DeleteSecretResponse\x12R\n" +
	"\tGetSecret\x12!.secretkeeper.v1.GetSecretRequest\x1a\".secretkeeper.v1.GetSecretResponse\x12X\n" +
	"\vListSecrets\x12#.secretkeeper.v1.ListSecretsRequest\x1a$.secretkeeper.v1.ListSecretsResponseB3Z1github.com/onbehalfofhim/secrets-keeper/api/protob\x06proto3"

var file_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_secret_proto_goTypes = []any{
	(*Secret)(nil),               // 0: secretkeeper.v1.Secret
	(*TextSecret)(nil),           // 1: secretkeeper.v1.TextSecret
	(*LoginPasswordSecret)(nil),  // 2: secretkeeper.v1.LoginPasswordSecret
	(*BankCardSecret)(nil),       // 3: secretkeeper.v1.BankCardSecret
	(*BinarySecret)(nil),         // 4: secretkeeper.v1.BinarySecret
	(*CreateSecretRequest)(nil),  // 5: secretkeeper.v1.CreateSecretRequest
	(*CreateSecretResponse)(nil), // 6: secretkeeper.v1.CreateSecretResponse
	(*UpdateSecretRequest)(nil),  // 7: secretkeeper.v1.UpdateSecretRequest
	(*UpdateSecretResponse)(nil), // 8: secretkeeper.v1.UpdateSecretResponse
	(*DeleteSecretRequest)(nil),  // 9: secretkeeper.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil), // 10: secretkeeper.v1.DeleteSecretResponse
	(*GetSecretRequest)(nil),     // 11: secretkeeper.v1.GetSecretRequest
	(*GetSecretResponse)(nil),    // 12: secretkeeper.v1.GetSecretResponse
	(*ListSecretsRequest)(nil),   // 13: secretkeeper.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),  // 14: secretkeeper.v1.ListSecretsResponse
	(*SecretMetadata)(nil),       // 15: secretkeeper.v1.SecretMetadata
}
var file_secret_proto_depIdxs = []int32{
	15, // 0: secretkeeper.v1.Secret.metadata:type_name -> secretkeeper.v1.SecretMetadata
	1,  // 1: secretkeeper.v1.Secret.text:type_name -> secretkeeper.v1.TextSecret
	2,  // 2: secretkeeper.v1.Secret.login_password:type_name -> secretkeeper.v1.LoginPasswordSecret
	3,  // 3: secretkeeper.v1.Secret.bank_card:type_name -> secretkeeper.v1.BankCardSecret
	4,  // 4: secretkeeper.v1.Secret.binary:type_name -> secretkeeper.v1.BinarySecret
	0,  // 5: secretkeeper.v1.CreateSecretRequest.secret:type_name -> secretkeeper.v1.Secret
	0,  // 6: secretkeeper.v1.UpdateSecretRequest.secret:type_name -> secretkeeper.v1.Secret
	0,  // 7: secretkeeper.v1.GetSecretResponse.secret:type_name -> secretkeeper.v1.Secret
	15, // 8: secretkeeper.v1.ListSecretsResponse.secrets:type_name -> secretkeeper.v1.SecretMetadata
	5,  // 9: secretkeeper.v1.SecretService.CreateSecret:input_type -> secretkeeper.v1.CreateSecretRequest
	7,  // 10: secretkeeper.v1.SecretService.UpdateSecret:input_type -> secretkeeper.v1.UpdateSecretRequest
	9,  // 11: secretkeeper.v1.SecretService.DeleteSecret:input_type -> secretkeeper.v1.DeleteSecretRequest
	11, // 12: secretkeeper.v1.SecretService.GetSecret:input_type -> secretkeeper.v1.GetSecretRequest
	13, // 13: secretkeeper.v1.SecretService.ListSecrets:input_type -> secretkeeper.v1.ListSecretsRequest
	6,  // 14: secretkeeper.v1.SecretService.CreateSecret:output_type -> secretkeeper.v1.CreateSecretResponse
	8,  // 15: secretkeeper.v1.SecretService.UpdateSecret:output_type -> secretkeeper.v1.UpdateSecretResponse
	10, // 16: secretkeeper.v1.SecretService.DeleteSecret:output_type -> secretkeeper.v1.DeleteSecretResponse
	12, // 17: secretkeeper.v1.SecretService.GetSecret:output_type -> secretkeeper.v1.GetSecretResponse
	14, // 18: secretkeeper.v1.SecretService.ListSecrets:output_type -> secretkeeper.v1.ListSecretsResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_secret_proto_init() }
func file_secret_proto_init() {
	if File_secret_proto != nil {
		return
	}
	file_common_proto_init()
	file_secret_proto_msgTypes[0].OneofWrappers = []any{
		(*secret_Text)(nil),
		(*secret_LoginPassword)(nil),
		(*secret_BankCard)(nil),
		(*secret_Binary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secret_proto_rawDesc), len(file_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secret_proto_goTypes,
		DependencyIndexes: file_secret_proto_depIdxs,
		MessageInfos:      file_secret_proto_msgTypes,
	}.Build()
	File_secret_proto = out.File
	file_secret_proto_goTypes = nil
	file_secret_proto_depIdxs = nil
}
